import React, { useState, useEffect } from "react";
import { Sparkles, Loader2, CheckCircle2, Circle, Save } from "lucide-react";
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';

import { Task, User, Subtask } from "@/types";
import { AI_BASE_URL, apiGet, apiPut, apiPost } from "@/lib/apiClient";
import { useLocalization } from "@/contexts/LocalizationContext";

interface TaskDetailsPanelProps {
  task: Task;
  onClose: () => void;
}

export default function TaskDetailsPanel({ task, onClose }: TaskDetailsPanelProps) {
  const { isRtl } = useLocalization();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [generatedSubtasks, setGeneratedSubtasks] = useState<Subtask[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [assigneeId, setAssigneeId] = useState<string>("");
  const [status, setStatus] = useState<string>("");
  const [priority, setPriority] = useState<number>(0);
  const [storyPoints, setStoryPoints] = useState<number>(0);

  const editor = useEditor({
    extensions: [StarterKit],
    content: '',
    editorProps: {
      attributes: {
        class: 'prose prose-sm sm:prose lg:prose-lg xl:prose-2xl mx-auto focus:outline-none bg-[#f8fafc] p-4 rounded-md min-h-[150px]',
      },
    },
  });

  useEffect(() => {
    if (task) {
      setTimeout(() => { editor?.commands.setContent(task.Description || '');
      setAssigneeId(task.AssigneeID || "");
      setStatus(task.Status || "todo");
      setPriority(task.Priority || 0);
      setStoryPoints(task.StoryPoints || 0); }, 0);
    }
  }, [task, editor]);

  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const data = await apiGet(`/users/search?q=`) as unknown as User[];
        setUsers(data || []);
      } catch (e) {
        console.error(e);
      }
    };
    fetchUsers();
  }, []);

  const handleSaveChanges = async () => {
    setIsSaving(true);
    try {
      await apiPut(`/tasks/${task.ID}`, {
        description: editor?.getHTML(),
        assignee_id: assigneeId === "unassigned" ? "" : assigneeId,
        status: status,
        priority: priority,
        story_points: storyPoints
      });
      window.dispatchEvent(new CustomEvent("ws-message", { detail: { type: "task_updated" } }));
      onClose();
    } catch (error) {
      console.error(error);
    } finally {
      setIsSaving(false);
    }
  };

  if (!task) return null;

  const handleAIBreakdown = async () => {
    setIsGenerating(true);
    try {
      const data = await apiPost(`/ai/generate-subtasks`, {
        title: task.Title,
        description: editor?.getText() || ""
      }, AI_BASE_URL) as unknown as { subtasks: string[] };
      if (data.subtasks && Array.isArray(data.subtasks) && data.subtasks.length > 0) {
        setGeneratedSubtasks(data.subtasks.map((t: string, idx: number) => ({
            id: String(idx + 1),
            title: t,
            done: false
          })));
          setIsGenerating(false);
          return;
      }
    } catch (e) {
      console.error("AI Subtask service error:", e);
    }
    // Fallback heuristic if AI service not connected
    setGeneratedSubtasks([
      { id: "1", title: `Architecture & scopes breakdown for: ${task.Title}`, done: false },
      { id: "2", title: `Database models and API endpoint design`, done: false },
      { id: "3", title: `Frontend interactive UI components & state coupling`, done: false },
      { id: "4", title: `Automated test coverage and security verification`, done: false }
    ]);
    setIsGenerating(false);
  };

  const handleAddSubtasks = async () => {
    setIsSaving(true);

    try {
      // Create subtasks that are NOT marked as 'done'
      const tasksToCreate = generatedSubtasks.filter(st => !st.done);
      for (const st of tasksToCreate) {
        await apiPost(`/tasks`, {
          project_id: task.ProjectID,
          title: st.title,
          description: "Generated by AI from parent task",
          parent_id: task.ID
        });
      }
      
      // Clear and close
      setGeneratedSubtasks([]);
      setIsSaving(false);
      
      // Trigger global refresh to update Kanban board
      window.dispatchEvent(new CustomEvent("ws-message", { detail: { type: "task_created" } }));
      
    } catch (error) {
      console.error("Failed to save subtasks", error);
      setIsSaving(false);
    }
  };

  return (
    <div className="absolute top-0 end-0 h-full w-[400px] bg-white shadow-2xl border-s border-slate-200 z-50 flex flex-col animate-in slide-in-from-right duration-200">
      <div className="flex items-center justify-between p-4 border-b border-slate-100">
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-slate-400">TASK-{task.ID.substring(0,4)}</span>
        </div>
        <button 
          onClick={onClose}
          className="p-2 hover:bg-slate-100 rounded-md text-slate-500 transition-colors"
          title={isRtl ? "إغلاق اللوحة" : "Close Panel"}
          aria-label={isRtl ? "إغلاق اللوحة" : "Close Panel"}
        >
          <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12.8536 2.85355C13.0488 2.65829 13.0488 2.34171 12.8536 2.14645C12.6583 1.95118 12.3417 1.95118 12.1464 2.14645L7.5 6.79289L2.85355 2.14645C2.65829 1.95118 2.34171 1.95118 2.14645 2.14645C1.95118 2.34171 1.95118 2.65829 2.14645 2.85355L6.79289 7.5L2.14645 12.1464C1.95118 12.3417 1.95118 12.6583 2.14645 12.8536C2.34171 13.0488 2.65829 13.0488 2.85355 12.8536L7.5 8.20711L12.1464 12.8536C12.3417 13.0488 12.6583 13.0488 12.8536 12.8536C13.0488 12.6583 13.0488 12.3417 12.8536 12.1464L8.20711 7.5L12.8536 2.85355Z" fill="currentColor" fillRule="evenodd" clipRule="evenodd"></path>
          </svg>
        </button>
      </div>
      <div className="p-6 overflow-y-auto flex-1">
        <h2 className="text-2xl font-bold text-slate-900 mb-6 leading-tight">{task.Title}</h2>
        
        <div className="space-y-6">
          <div className="grid grid-cols-3 gap-y-4 text-sm items-center">
            <div className="text-slate-500">{isRtl ? "الحالة" : "Status"}</div>
            <div className="col-span-2">
              <select 
                aria-label={isRtl ? "حالة المهمة" : "Task Status"}
                value={status}
                onChange={(e) => setStatus(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-100 border-none rounded-md font-medium text-slate-700 capitalize focus:ring-0 outline-none"
              >
                <option value="todo">{isRtl ? "قيد الانتظار" : "To Do"}</option>
                <option value="in_progress">{isRtl ? "قيد التنفيذ" : "In Progress"}</option>
                <option value="review">{isRtl ? "مراجعة" : "Review"}</option>
                <option value="done">{isRtl ? "مكتملة" : "Done"}</option>
              </select>
            </div>
            
            <div className="text-slate-500">{isRtl ? "المُسند إليه" : "Assignee"}</div>
            <div className="col-span-2 flex items-center gap-2">
              <select 
                aria-label={isRtl ? "المُسند إليه" : "Assignee"}
                value={assigneeId}
                onChange={(e) => setAssigneeId(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-100 border-none rounded-md font-medium text-slate-700 focus:ring-0 outline-none"
              >
                <option value="unassigned">{isRtl ? "غير مُسند" : "Unassigned"}</option>
                {users.map(u => (
                  <option key={u.id} value={u.id}>{u.email}</option>
                ))}
              </select>
            </div>

            <div className="text-slate-500">{isRtl ? "الأولوية" : "Priority"}</div>
            <div className="col-span-2">
              <select 
                aria-label={isRtl ? "أولوية المهمة" : "Task Priority"}
                value={priority}
                onChange={(e) => setPriority(parseInt(e.target.value))}
                className="w-full px-3 py-1.5 bg-slate-100 border-none rounded-md font-medium text-slate-700 focus:ring-0 outline-none"
              >
                <option value={0}>{isRtl ? "عادية" : "Normal"}</option>
                <option value={1}>{isRtl ? "عالية" : "High"}</option>
                <option value={2}>{isRtl ? "عاجلة" : "Urgent"}</option>
              </select>
            </div>

            <div className="text-slate-500">{isRtl ? "نقاط الجهد" : "Story Points"}</div>
            <div className="col-span-2">
              <select 
                aria-label={isRtl ? "نقاط الجهد" : "Story Points"}
                value={storyPoints}
                onChange={(e) => setStoryPoints(parseInt(e.target.value))}
                className="w-full px-3 py-1.5 bg-slate-100 border-none rounded-md font-medium text-slate-700 focus:ring-0 outline-none"
              >
                <option value={0}>0 (Unestimated)</option>
                <option value={1}>1 Point</option>
                <option value={2}>2 Points</option>
                <option value={3}>3 Points</option>
                <option value={5}>5 Points</option>
                <option value={8}>8 Points</option>
                <option value={13}>13 Points</option>
                <option value={21}>21 Points</option>
              </select>
            </div>
          </div>

          <div className="w-full h-px bg-slate-100" />

          <div>
            <h3 className="text-sm font-semibold text-slate-900 mb-2">{isRtl ? "الوصف" : "Description"}</h3>
            <EditorContent editor={editor} />
          </div>

          <div className="w-full h-px bg-slate-100" />

          <div>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-slate-900">{isRtl ? "المهام الفرعية" : "Subtasks"}</h3>
              {generatedSubtasks.length === 0 && !isGenerating && (
                <button 
                  onClick={handleAIBreakdown}
                  className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 bg-brand-light text-brand rounded-md hover:bg-brand-light transition-colors border border-brand-light"
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  {isRtl ? "تقسيم بالذكاء الاصطناعي" : "Break down with AI"}
                </button>
              )}
            </div>

            {isGenerating && (
              <div className="flex flex-col items-center justify-center py-8 space-y-3 bg-slate-50 rounded-lg border border-slate-100 border-dashed">
                <Loader2 className="w-6 h-6 text-brand animate-spin" />
                <p className="text-sm text-slate-500 font-medium">{isRtl ? "يقوم الذكاء الاصطناعي بتحليل سياق المهمة..." : "AI is analyzing task context..."}</p>
              </div>
            )}

            {generatedSubtasks.length > 0 && (
              <div className="space-y-2">
                {generatedSubtasks.map((st) => (
                  <div key={st.id} className="flex items-start gap-3 p-3 rounded-lg border border-slate-100 bg-slate-50 hover:bg-slate-100 transition-colors group cursor-pointer" onClick={() => {
                    setGeneratedSubtasks(prev => prev.map(p => p.id === st.id ? { ...p, done: !p.done } : p));
                  }}>
                    <button className="mt-0.5">
                      {st.done ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                      ) : (
                        <Circle className="w-4 h-4 text-slate-300 group-hover:text-brand" />
                      )}
                    </button>
                    <span className={`text-sm ${st.done ? 'text-slate-400 line-through' : 'text-slate-700 font-medium'}`}>
                      {st.title}
                    </span>
                  </div>
                ))}
                
                <button 
                  onClick={handleAddSubtasks}
                  disabled={isSaving}
                  className="mt-2 text-xs font-semibold text-brand hover:text-brand-dark transition-colors w-full text-center py-2 flex items-center justify-center gap-2"
                >
                  {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : (isRtl ? "+ أضف هذه إلى اللوحة" : "+ Add these to board")}
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
      
      <div className="p-4 border-t border-slate-100 bg-slate-50">
        <button 
          onClick={handleSaveChanges}
          disabled={isSaving}
          className="w-full py-2 bg-brand text-white rounded-md font-medium hover:bg-brand transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
        >
          {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
          {isRtl ? "حفظ التغييرات" : "Save Changes"}
        </button>
      </div>
    </div>
  );
}
