#!/usr/bin/env bash
# gen-secrets.sh — توليد أسرار إنتاج قوية لـ Septimus OS
# يطبع الأسطر إلى stdout للمراجعة (لا يكتب .env تلقائياً حتى لا يدهس ملفك).
# الاستخدام:
#   ./scripts/gen-secrets.sh              # اطبع الأسرار
#   ./scripts/gen-secrets.sh >> .env      # ألحقها بملف .env بعد المراجعة
set -euo pipefail

hex()  { openssl rand -hex "${1:-32}"; }   # 32 bytes -> 64 hex chars
b64()  { openssl rand -base64 "${1:-32}"; }

cat <<EOF
# ─── Generated by scripts/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) ───
# راجعها ثم ألصقها في .env (لا تلتزمها في git).

# Core auth / crypto (SETTINGS_ENC_KEY يُشتق عبر sha256 فأي طول قوي مقبول)
JWT_SECRET=$(hex 32)
SETTINGS_ENC_KEY=$(hex 32)
INTERNAL_API_TOKEN=$(hex 24)

# Centrifugo realtime
CENTRIFUGO_SECRET=$(hex 32)
CENTRIFUGO_API_KEY=$(hex 24)
CENTRIFUGO_ADMIN_PASSWORD=$(hex 12)
CENTRIFUGO_ADMIN_SECRET=$(hex 24)

# Postgres (بدّل DB_DSN و POSTGRES_PASSWORD معاً إن غيّرتهما)
POSTGRES_PASSWORD=$(hex 16)

# ── اختياري: Langfuse (فعّلها فقط إن استخدمت التتبع) ──
# LANGFUSE_NEXTAUTH_SECRET=$(b64 32)
# LANGFUSE_SALT=$(b64 32)
# LANGFUSE_ENCRYPTION_KEY=$(hex 32)
EOF

cat >&2 <<'EOF'

⚠️  تذكير:
  • هذه أسرار حسّاسة — لا تلتزمها في git ولا تشاركها.
  • إن غيّرت POSTGRES_PASSWORD حدّث DB_DSN ليطابقه.
  • لا تُدوّر N8N_ENCRYPTION_KEY بعد أول إقلاع (يفكّ تشفير بيانات الاعتماد المحفوظة).
  • بعد التحديث: docker compose up -d --build
EOF
